"""
FRLG Shiny Starter — 3DS

Auto-generated by GamePRo Script Builder.
Adjust the timing constants at the top of the class to tune the script.
"""

import json
import os
import sys
import time

from scripts.base_script import BaseScript


class FrlgShinyStarter(BaseScript):
    NAME = 'FRLG Shiny Starter'
    DESCRIPTION = "Auto-generated script for 3DS."

    # ── Timing constants (seconds) ──────────────────────────────────────
    SOFT_RESET_1_DELAY = 1.63
    X_2_DELAY = 1.16
    A_3_DELAY = 1.84
    A_4_DELAY = 1.23
    A_5_DELAY = 6.71
    A_6_DELAY = 4.76
    A_7_DELAY = 3.35
    A_8_DELAY = 2.75
    B_9_DELAY = 3.49
    A_10_DELAY = 1.88
    A_11_DELAY = 1.92
    A_12_DELAY = 2.79
    A_13_DELAY = 5.76
    B_14_DELAY = 3.69
    A_15_DELAY = 4.56
    X_16_DELAY = 1.15
    A_17_DELAY = 1.75
    A_18_DELAY = 1.30
    A_19_DELAY = 0.00
    DETECT_1_WINDOW    = 5.0
    DETECT_1_INTERVAL  = 0.08
    DETECT_1_TOLERANCE = 30
    DETECT_1_TARGET   = [255.0, 216.0, 95.0]  # R, G, B target colour (right-click reference image)
    DETECT_1_PX_THRESHOLD = 10   # min matching pixels to trigger

    # ── Video panel dimensions (must match VideoPanel constants) ─────────
    _PANEL_W = 640
    _PANEL_H = 480

    def __init__(self):
        super().__init__()
        self._cal = None

    def run(self, controller, frame_grabber, stop_event, log, request_calibration):
        log('Script started.')

        # ── 4-corner screen calibration (every run) ───────────────────────
        log('Click the four corners of the 3DS screen in any order.')
        warp_info = request_calibration(
            'Click the 4 corners of the 3DS screen', mode='corners'
        )
        if stop_event.is_set() or warp_info is None:
            log('Script stopped.')
            return
        log(f'Screen calibrated ({warp_info["out_w"]}×{warp_info["out_h"]} px).')

        self._load_cal()
        count = 0

        while not stop_event.is_set():
            # Step 1: [Home]
            controller.soft_reset()
            if not self.wait(self.SOFT_RESET_1_DELAY, stop_event): break

            # Step 2: [X]
            controller.press_x()
            if not self.wait(self.X_2_DELAY, stop_event): break

            # Step 3: [A]
            controller.press_a()
            if not self.wait(self.A_3_DELAY, stop_event): break

            # Step 4: [A]
            controller.press_a()
            if not self.wait(self.A_4_DELAY, stop_event): break

            # Step 5: [A]
            controller.press_a()
            if not self.wait(self.A_5_DELAY, stop_event): break

            # Step 6: [A]
            controller.press_a()
            if not self.wait(self.A_6_DELAY, stop_event): break

            # Step 7: [A]
            controller.press_a()
            if not self.wait(self.A_7_DELAY, stop_event): break

            # Step 8: [A]
            controller.press_a()
            if not self.wait(self.A_8_DELAY, stop_event): break

            # Step 9: [B]
            controller.press_b()
            if not self.wait(self.B_9_DELAY, stop_event): break

            # Step 10: [A]
            controller.press_a()
            if not self.wait(self.A_10_DELAY, stop_event): break

            # Step 11: [A]
            controller.press_a()
            if not self.wait(self.A_11_DELAY, stop_event): break

            # Step 12: [A]
            controller.press_a()
            if not self.wait(self.A_12_DELAY, stop_event): break

            # Step 13: [A]
            controller.press_a()
            if not self.wait(self.A_13_DELAY, stop_event): break

            # Step 14: [B]
            controller.press_b()
            if not self.wait(self.B_14_DELAY, stop_event): break

            # Step 15: [A]
            controller.press_a()
            if not self.wait(self.A_15_DELAY, stop_event): break

            # Step 16: [X]
            controller.press_x()
            if not self.wait(self.X_16_DELAY, stop_event): break

            # Step 17: [A]
            controller.press_a()
            if not self.wait(self.A_17_DELAY, stop_event): break

            # Step 18: [A]
            controller.press_a()
            if not self.wait(self.A_18_DELAY, stop_event): break

            # Step 19: [A]
            controller.press_a()

            # Step 20: Detect — calibrate region on first run
            if not self._cal or 'region' not in self._cal:
                log('Draw a box around the shiny star area.')
                region_canvas = request_calibration(
                    'Draw a box around the shiny star area.'
                )
                if stop_event.is_set(): break
                region = self._canvas_to_warp(region_canvas, warp_info)
                if self._cal is None:
                    self._cal = {}
                self._cal['region'] = list(region)
                self._save_cal()
                log('Detection region saved.')

            x, y, w, h = self._cal['region']

            # Flash the detection box for 1 second so the user can see it
            cx, cy, cw, ch = self._warp_to_canvas((x, y, w, h), warp_info)
            frame_grabber.set_detect_overlay(cx, cy, cw, ch)
            if not self.wait(1.0, stop_event):
                frame_grabber.clear_detect_overlay()
                break
            frame_grabber.clear_detect_overlay()

            tr, tg, tb = self.DETECT_1_TARGET
            tol = self.DETECT_1_TOLERANCE
            result = self._poll_target_color(
                frame_grabber, stop_event, warp_info,
                x, y, w, h, tr, tg, tb, tol,
                self.DETECT_1_PX_THRESHOLD,
                self.DETECT_1_WINDOW, self.DETECT_1_INTERVAL, log)
            if stop_event.is_set(): break
            if result is not None:
                log(f'DETECTED! {result} px match target colour (threshold: {self.DETECT_1_PX_THRESHOLD}).')
                stop_event.wait()
                break

            count += 1
            log(f'Attempt {count} complete.')

        log('Script stopped.')

    # ── Calibration ──────────────────────────────────────────────────────

    def _cal_path(self):
        base = (os.path.dirname(sys.executable) if getattr(sys, 'frozen', False)
                else os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        cal_dir = os.path.join(base, 'calibration')
        os.makedirs(cal_dir, exist_ok=True)
        return os.path.join(cal_dir, 'frlg_shiny_starter.json')

    def _load_cal(self):
        try:
            with open(self._cal_path(), 'r') as f:
                self._cal = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            self._cal = None

    def _save_cal(self):
        with open(self._cal_path(), 'w') as f:
            json.dump(self._cal, f)

    def _canvas_to_warp(self, canvas_rect, warp_info):
        """Convert a rectangle in canvas pixels to warped-frame pixels."""
        cx, cy, cw, ch = canvas_rect
        scale = min(self._PANEL_W / warp_info['out_w'],
                    self._PANEL_H / warp_info['out_h'])
        x_off = (self._PANEL_W - warp_info['out_w'] * scale) / 2
        y_off = (self._PANEL_H - warp_info['out_h'] * scale) / 2
        x = max(0, int((cx - x_off) / scale))
        y = max(0, int((cy - y_off) / scale))
        w = max(1, int(cw / scale))
        h = max(1, int(ch / scale))
        return x, y, w, h

    def _warp_to_canvas(self, warp_rect, warp_info):
        """Convert a rectangle in warped-frame pixels to canvas pixels."""
        x, y, w, h = warp_rect
        scale = min(self._PANEL_W / warp_info['out_w'],
                    self._PANEL_H / warp_info['out_h'])
        x_off = (self._PANEL_W - warp_info['out_w'] * scale) / 2
        y_off = (self._PANEL_H - warp_info['out_h'] * scale) / 2
        cx = int(x * scale + x_off)
        cy = int(y * scale + y_off)
        cw = max(1, int(w * scale))
        ch = max(1, int(h * scale))
        return cx, cy, cw, ch

    def _poll_target_color(self, frame_grabber, stop_event, warp_info,
                           x, y, w, h, tr, tg, tb, tolerance,
                           px_threshold, window, interval, log=None):
        """Target colour detection on the perspective-corrected frame."""
        deadline = time.time() + window
        next_log = time.time() + 2.0
        while time.time() < deadline:
            if stop_event.is_set():
                return None
            frame = frame_grabber.get_latest_frame()
            if frame is not None:
                frame = self.warp_frame(frame, warp_info)
                n = self.count_target_pixels(
                    frame, x, y, w, h, tr, tg, tb, tolerance)
                if log and time.time() >= next_log:
                    log(f'Watching... {n} px match target  (threshold: {px_threshold}  tolerance: {tolerance})')
                    next_log = time.time() + 2.0
                if n >= px_threshold:
                    time.sleep(interval * 2)
                    frame2 = frame_grabber.get_latest_frame()
                    if frame2 is not None:
                        frame2 = self.warp_frame(frame2, warp_info)
                        n2 = self.count_target_pixels(
                            frame2, x, y, w, h, tr, tg, tb, tolerance)
                        if n2 >= px_threshold:
                            return n2
            time.sleep(interval)
        return None
