"""
FRLG Shiny Lapras — Switch / Switch 2

Auto-generated by GamePRo Script Builder.
Adjust the timing constants at the top of the class to tune the script.
"""

import time

from scripts.base_script import BaseScript


class FrlgShinyLapras(BaseScript):
    NAME = 'FRLG Shiny Lapras'
    DESCRIPTION = "Auto-generated script for Switch / Switch 2."

    # ── Timing constants (seconds) ──────────────────────────────────────
    # ── Block 1 ──
    SOFT_RESET_1_DELAY = 2.12
    X_2_DELAY = 1.47
    A_3_DELAY = 2.59
    A_4_DELAY = 1.63
    A_5_DELAY = 6.99
    A_6_DELAY = 4.90
    A_7_DELAY = 4.00
    A_8_DELAY = 2.62
    B_9_DELAY = 3.10
    # ── Block 2 ──
    A_10_DELAY = 1.59
    A_11_DELAY = 1.22
    A_12_DELAY = 1.94
    A_13_DELAY = 3.36
    B_14_DELAY = 1.65
    A_15_DELAY = 1.66
    A_16_DELAY = 1.58
    A_17_DELAY = 1.86
    A_18_DELAY = 1.68
    X_19_DELAY = 2.32
    DOWN_20_DELAY = 1.47
    A_21_DELAY = 2.88
    RIGHT_22_DELAY = 1.37
    A_23_DELAY = 1.56
    A_24_DELAY = 4.20
    DETECT_1_WINDOW    = 6.0
    DETECT_1_INTERVAL  = 0.08
    DETECT_1_TOLERANCE = 25
    DETECT_1_TARGET   = [253.0, 209.0, 82.0]  # R, G, B target colour (right-click reference image)
    DETECT_1_PX_THRESHOLD = 10   # min matching pixels to trigger
    DETECT_1_REGION   = [273, 162, 42, 28]   # x, y, w, h in frame pixels

    # ── Video panel dimensions (must match VideoPanel constants) ─────────
    _PANEL_W = 640
    _PANEL_H = 480

    def run(self, controller, frame_grabber, stop_event, log, request_calibration):
        log('Script started.')

        # ── 4-corner screen calibration (every run) ───────────────────────
        log('Click the four corners of the Switch / Switch 2 screen in any order.')
        warp_info = request_calibration(
            'Click the 4 corners of the Switch / Switch 2 screen', mode='corners'
        )
        if stop_event.is_set() or warp_info is None:
            log('Script stopped.')
            return
        log(f'Screen calibrated ({warp_info["out_w"]}×{warp_info["out_h"]} px).')
        count = 0

        while not stop_event.is_set():
            if not self._block_block_1(controller, frame_grabber, stop_event, log, request_calibration, warp_info): break
            if not self._block_block_2(controller, frame_grabber, stop_event, log, request_calibration, warp_info): break
            count += 1
            log(f'Attempt {count} complete.')

        log('Script stopped.')

    def _block_block_1(self, controller, frame_grabber, stop_event, log, request_calibration, warp_info):
        """Block: Block 1"""
        # Step 1: [Home]
        controller.soft_reset()
        if not self.wait(self.SOFT_RESET_1_DELAY, stop_event): return False

        # Step 2: [X]
        controller.press_x()
        if not self.wait(self.X_2_DELAY, stop_event): return False

        # Step 3: [A]
        controller.press_a()
        if not self.wait(self.A_3_DELAY, stop_event): return False

        # Step 4: [A]
        controller.press_a()
        if not self.wait(self.A_4_DELAY, stop_event): return False

        # Step 5: [A]
        controller.press_a()
        if not self.wait(self.A_5_DELAY, stop_event): return False

        # Step 6: [A]
        controller.press_a()
        if not self.wait(self.A_6_DELAY, stop_event): return False

        # Step 7: [A]
        controller.press_a()
        if not self.wait(self.A_7_DELAY, stop_event): return False

        # Step 8: [A]
        controller.press_a()
        if not self.wait(self.A_8_DELAY, stop_event): return False

        # Step 9: [B]
        controller.press_b()
        if not self.wait(self.B_9_DELAY, stop_event): return False

        return True

    def _block_block_2(self, controller, frame_grabber, stop_event, log, request_calibration, warp_info):
        """Block: Block 2"""
        # Step 10: [A]
        controller.press_a()
        if not self.wait(self.A_10_DELAY, stop_event): return False

        # Step 11: [A]
        controller.press_a()
        if not self.wait(self.A_11_DELAY, stop_event): return False

        # Step 12: [A]
        controller.press_a()
        if not self.wait(self.A_12_DELAY, stop_event): return False

        # Step 13: [A]
        controller.press_a()
        if not self.wait(self.A_13_DELAY, stop_event): return False

        # Step 14: [B]
        controller.press_b()
        if not self.wait(self.B_14_DELAY, stop_event): return False

        # Step 15: [A]
        controller.press_a()
        if not self.wait(self.A_15_DELAY, stop_event): return False

        # Step 16: [A]
        controller.press_a()
        if not self.wait(self.A_16_DELAY, stop_event): return False

        # Step 17: [A]
        controller.press_a()
        if not self.wait(self.A_17_DELAY, stop_event): return False

        # Step 18: [A]
        controller.press_a()
        if not self.wait(self.A_18_DELAY, stop_event): return False

        # Step 19: [X]
        controller.press_x()
        if not self.wait(self.X_19_DELAY, stop_event): return False

        # Step 20: [↓]
        controller.press_down()
        if not self.wait(self.DOWN_20_DELAY, stop_event): return False

        # Step 21: [A]
        controller.press_a()
        if not self.wait(self.A_21_DELAY, stop_event): return False

        # Step 22: [→]
        controller.press_right()
        if not self.wait(self.RIGHT_22_DELAY, stop_event): return False

        # Step 23: [A]
        controller.press_a()
        if not self.wait(self.A_23_DELAY, stop_event): return False

        # Step 24: [A]
        controller.press_a()
        if not self.wait(self.A_24_DELAY, stop_event): return False

        # Step 25: Detect
        x, y, w, h = self._frame_to_warp(self.DETECT_1_REGION, warp_info)
        tr, tg, tb = self.DETECT_1_TARGET
        tol = self.DETECT_1_TOLERANCE
        frame_grabber.set_detect_overlay(*self._warp_to_canvas((x, y, w, h), warp_info))
        result = self._poll_target_color(
            frame_grabber, stop_event, warp_info,
            x, y, w, h, tr, tg, tb, tol,
            self.DETECT_1_PX_THRESHOLD,
            self.DETECT_1_WINDOW, self.DETECT_1_INTERVAL, log)
        frame_grabber.clear_detect_overlay()
        if stop_event.is_set(): return False
        if result is not None:
            log(f'DETECTED! {result} px match target colour (threshold: {self.DETECT_1_PX_THRESHOLD}).')
            stop_event.wait()
            return False

        return True

    def _poll_target_color(self, frame_grabber, stop_event, warp_info,
                          x, y, w, h, tr, tg, tb, tolerance,
                          px_threshold, window, interval, log=None):
        """Target colour detection — fires when >= px_threshold pixels
        match the target colour (tr, tg, tb) within tolerance.
        Use for detecting a specific sparkle/highlight colour.
        """
        deadline = time.time() + window
        next_log = time.time() + 2.0
        while time.time() < deadline:
            if stop_event.is_set():
                return None
            frame = frame_grabber.get_latest_frame()
            if frame is not None:
                frame = self.warp_frame(frame, warp_info)
                n = self.count_target_pixels(
                    frame, x, y, w, h, tr, tg, tb, tolerance)
                if log and time.time() >= next_log:
                    log(f'Watching... {n} px match target  (threshold: {px_threshold}  tolerance: {tolerance})')
                    next_log = time.time() + 2.0
                if n >= px_threshold:
                    time.sleep(interval * 2)
                    frame2 = frame_grabber.get_latest_frame()
                    if frame2 is not None:
                        frame2 = self.warp_frame(frame2, warp_info)
                        n2 = self.count_target_pixels(
                            frame2, x, y, w, h, tr, tg, tb, tolerance)
                        if n2 >= px_threshold:
                            return n2
            time.sleep(interval)
        return None

    # ── Coordinate conversion helpers ─────────────────────────────────────

    def _frame_to_warp(self, frame_rect, warp_info):
        """Convert a rectangle in full-frame pixels to warped-frame pixels."""
        import cv2, numpy as np
        fx, fy, fw, fh = frame_rect
        corners = np.array([[fx, fy], [fx+fw, fy],
                            [fx+fw, fy+fh], [fx, fy+fh]],
                           dtype=np.float32).reshape(-1, 1, 2)
        wc = cv2.perspectiveTransform(corners, warp_info['matrix'])
        x_min = float(wc[:, :, 0].min())
        x_max = float(wc[:, :, 0].max())
        y_min = float(wc[:, :, 1].min())
        y_max = float(wc[:, :, 1].max())
        return int(x_min), int(y_min), max(1, int(x_max - x_min)), max(1, int(y_max - y_min))

    def _canvas_to_warp(self, canvas_rect, warp_info):
        """Convert a rectangle in canvas pixels to warped-frame pixels."""
        cx, cy, cw, ch = canvas_rect
        scale = min(self._PANEL_W / warp_info['out_w'],
                    self._PANEL_H / warp_info['out_h'])
        x_off = (self._PANEL_W - warp_info['out_w'] * scale) / 2
        y_off = (self._PANEL_H - warp_info['out_h'] * scale) / 2
        x = max(0, int((cx - x_off) / scale))
        y = max(0, int((cy - y_off) / scale))
        w = max(1, int(cw / scale))
        h = max(1, int(ch / scale))
        return x, y, w, h

    def _warp_to_canvas(self, warp_rect, warp_info):
        """Convert a rectangle in warped-frame pixels to canvas pixels."""
        x, y, w, h = warp_rect
        scale = min(self._PANEL_W / warp_info['out_w'],
                    self._PANEL_H / warp_info['out_h'])
        x_off = (self._PANEL_W - warp_info['out_w'] * scale) / 2
        y_off = (self._PANEL_H - warp_info['out_h'] * scale) / 2
        cx = int(x * scale + x_off)
        cy = int(y * scale + y_off)
        cw = max(1, int(w * scale))
        ch = max(1, int(h * scale))
        return cx, cy, cw, ch
