"""
FRLG Shiny Deoxys — Switch / Switch 2

Auto-generated by GamePRo Script Builder.
Adjust the timing constants at the top of the class to tune the script.
"""

import random
import time

from scripts.base_script import BaseScript


class FrlgShinyDeoxys(BaseScript):
    NAME = 'FRLG Shiny Deoxys'
    DESCRIPTION = "Auto-generated script for Switch / Switch 2."

    # ── Timing constants (seconds) ──────────────────────────────────────
    A_1_DELAY = 15.98
    DETECT_1_WINDOW    = 6.0
    DETECT_1_INTERVAL  = 0.08
    DETECT_1_TOLERANCE = 25
    # ── Block 1 ──
    SOFT_RESET_3_DELAY = 1.78
    X_4_DELAY = 1.28
    A_5_DELAY = 2.35
    A_6_DELAY = 1.42
    RANDOM_7_MIN = 0.20   # random delay range
    RANDOM_7_MAX = 0.90
    A_8_DELAY = 6.93
    RANDOM_9_MIN = 0.20   # random delay range
    RANDOM_9_MAX = 0.90
    A_10_DELAY = 5.75
    RANDOM_11_MIN = 0.20   # random delay range
    RANDOM_11_MAX = 0.90
    A_12_DELAY = 3.81
    RANDOM_13_MIN = 0.20   # random delay range
    RANDOM_13_MAX = 0.90
    A_14_DELAY = 2.18
    RANDOM_15_MIN = 0.20   # random delay range
    RANDOM_15_MAX = 0.90
    B_16_DELAY = 3.29
    RANDOM_17_MIN = 0.20   # random delay range
    RANDOM_17_MAX = 0.90

    # ── Video panel dimensions (must match VideoPanel constants) ─────────
    _PANEL_W = 640
    _PANEL_H = 480

    def __init__(self):
        super().__init__()
        self._detect_cal = None

    def run(self, controller, frame_grabber, stop_event, log, request_calibration):
        log('Script started.')
        self._detect_cal = None  # reset region each run — asked on first cycle

        # ── 4-corner screen calibration (every run) ───────────────────────
        log('Click the four corners of the Switch / Switch 2 screen in any order.')
        warp_info = request_calibration(
            'Click the 4 corners of the Switch / Switch 2 screen', mode='corners'
        )
        if stop_event.is_set() or warp_info is None:
            log('Script stopped.')
            return
        log(f'Screen calibrated ({warp_info["out_w"]}×{warp_info["out_h"]} px).')
        count = 0

        while not stop_event.is_set():
            if not self._block_main(controller, frame_grabber, stop_event, log, request_calibration, warp_info): break
            if not self._block_block_1(controller, frame_grabber, stop_event, log, request_calibration, warp_info): break
            count += 1
            log(f'Attempt {count} complete.')

        log('Script stopped.')

    def _block_main(self, controller, frame_grabber, stop_event, log, request_calibration, warp_info):
        """Block: Main"""
        # Step 1: [A]
        controller.press_a()
        if not self.wait(self.A_1_DELAY, stop_event): return False

        # Step 2: Detect
        if self._detect_cal is None:
            self._do_calibrate(request_calibration, frame_grabber, stop_event, warp_info)
            if stop_event.is_set(): return False
        x, y, w, h = self._detect_cal['region']
        br, bg_c, bb = self._detect_cal['baseline']
        tol = self._detect_cal.get('tolerance', self.DETECT_1_TOLERANCE)
        frame_grabber.set_detect_overlay(*self._warp_to_canvas((x, y, w, h), warp_info))
        result = self._poll_region(
            frame_grabber, stop_event, warp_info,
            x, y, w, h, br, bg_c, bb, tol,
            self.DETECT_1_WINDOW, self.DETECT_1_INTERVAL, log)
        frame_grabber.clear_detect_overlay()
        if stop_event.is_set(): return False
        if result is not None:
            r2, g2, b2 = result
            log(f'DETECTED! avg RGB=({r2:.1f}, {g2:.1f}, {b2:.1f})')
            stop_event.wait()
            return False

        return True

    def _block_block_1(self, controller, frame_grabber, stop_event, log, request_calibration, warp_info):
        """Block: Block 1"""
        # Step 3: [Home]
        controller.soft_reset()
        if not self.wait(self.SOFT_RESET_3_DELAY, stop_event): return False

        # Step 4: [X]
        controller.press_x()
        if not self.wait(self.X_4_DELAY, stop_event): return False

        # Step 5: [A]
        controller.press_a()
        if not self.wait(self.A_5_DELAY, stop_event): return False

        # Step 6: [A]
        controller.press_a()
        if not self.wait(self.A_6_DELAY, stop_event): return False

        # Step 7: Random Wait
        if not self.wait(random.uniform(self.RANDOM_7_MIN, self.RANDOM_7_MAX), stop_event): return False

        # Step 8: [A]
        controller.press_a()
        if not self.wait(self.A_8_DELAY, stop_event): return False

        # Step 9: Random Wait
        if not self.wait(random.uniform(self.RANDOM_9_MIN, self.RANDOM_9_MAX), stop_event): return False

        # Step 10: [A]
        controller.press_a()
        if not self.wait(self.A_10_DELAY, stop_event): return False

        # Step 11: Random Wait
        if not self.wait(random.uniform(self.RANDOM_11_MIN, self.RANDOM_11_MAX), stop_event): return False

        # Step 12: [A]
        controller.press_a()
        if not self.wait(self.A_12_DELAY, stop_event): return False

        # Step 13: Random Wait
        if not self.wait(random.uniform(self.RANDOM_13_MIN, self.RANDOM_13_MAX), stop_event): return False

        # Step 14: [A]
        controller.press_a()
        if not self.wait(self.A_14_DELAY, stop_event): return False

        # Step 15: Random Wait
        if not self.wait(random.uniform(self.RANDOM_15_MIN, self.RANDOM_15_MAX), stop_event): return False

        # Step 16: [B]
        controller.press_b()
        if not self.wait(self.B_16_DELAY, stop_event): return False

        # Step 17: Random Wait
        if not self.wait(random.uniform(self.RANDOM_17_MIN, self.RANDOM_17_MAX), stop_event): return False

        return True

    def _do_calibrate(self, request_calibration, frame_grabber, stop_event, warp_info):
        """Called the first time the detect step is reached."""
        canvas_rect = request_calibration(
            "Draw a box around the area to watch for changes.")
        if stop_event.is_set():
            return
        x, y, w, h = self._canvas_to_warp(canvas_rect, warp_info)
        frame = frame_grabber.get_latest_frame()
        if frame is None:
            return
        frame = self.warp_frame(frame, warp_info)
        r, g, b = self.avg_rgb(frame, x, y, w, h)
        self._detect_cal = {'region': [x, y, w, h], 'baseline': [r, g, b], 'tolerance': 25}

    def _poll_region(self, frame_grabber, stop_event, warp_info,
                     x, y, w, h, br, bg_c, bb, tolerance, window, interval, log=None):
        """Avg RGB detection — fires when the region average shifts by > tolerance."""
        deadline = time.time() + window
        next_log = time.time() + 2.0
        while time.time() < deadline:
            if stop_event.is_set():
                return None
            frame = frame_grabber.get_latest_frame()
            if frame is not None:
                frame = self.warp_frame(frame, warp_info)
                r, g, b = self.avg_rgb(frame, x, y, w, h)
                if log and time.time() >= next_log:
                    log(f'Watching... avg RGB=({r:.1f}, {g:.1f}, {b:.1f})  '
                        f'Δ=({abs(r-br):.1f}, {abs(g-bg_c):.1f}, {abs(b-bb):.1f})  tolerance={tolerance}')
                    next_log = time.time() + 2.0
                if (abs(r-br) > tolerance or abs(g-bg_c) > tolerance
                        or abs(b-bb) > tolerance):
                    time.sleep(interval * 2)
                    frame2 = frame_grabber.get_latest_frame()
                    if frame2 is not None:
                        frame2 = self.warp_frame(frame2, warp_info)
                        r2, g2, b2 = self.avg_rgb(frame2, x, y, w, h)
                        if (abs(r2-br) > tolerance or abs(g2-bg_c) > tolerance
                                or abs(b2-bb) > tolerance):
                            return (r2, g2, b2)
            time.sleep(interval)
        return None

    # ── Coordinate conversion helpers ─────────────────────────────────────

    def _frame_to_warp(self, frame_rect, warp_info):
        """Convert a rectangle in full-frame pixels to warped-frame pixels."""
        import cv2, numpy as np
        fx, fy, fw, fh = frame_rect
        corners = np.array([[fx, fy], [fx+fw, fy],
                            [fx+fw, fy+fh], [fx, fy+fh]],
                           dtype=np.float32).reshape(-1, 1, 2)
        wc = cv2.perspectiveTransform(corners, warp_info['matrix'])
        x_min = float(wc[:, :, 0].min())
        x_max = float(wc[:, :, 0].max())
        y_min = float(wc[:, :, 1].min())
        y_max = float(wc[:, :, 1].max())
        return int(x_min), int(y_min), max(1, int(x_max - x_min)), max(1, int(y_max - y_min))

    def _canvas_to_warp(self, canvas_rect, warp_info):
        """Convert a rectangle in canvas pixels to warped-frame pixels."""
        cx, cy, cw, ch = canvas_rect
        scale = min(self._PANEL_W / warp_info['out_w'],
                    self._PANEL_H / warp_info['out_h'])
        x_off = (self._PANEL_W - warp_info['out_w'] * scale) / 2
        y_off = (self._PANEL_H - warp_info['out_h'] * scale) / 2
        x = max(0, int((cx - x_off) / scale))
        y = max(0, int((cy - y_off) / scale))
        w = max(1, int(cw / scale))
        h = max(1, int(ch / scale))
        return x, y, w, h

    def _warp_to_canvas(self, warp_rect, warp_info):
        """Convert a rectangle in warped-frame pixels to canvas pixels."""
        x, y, w, h = warp_rect
        scale = min(self._PANEL_W / warp_info['out_w'],
                    self._PANEL_H / warp_info['out_h'])
        x_off = (self._PANEL_W - warp_info['out_w'] * scale) / 2
        y_off = (self._PANEL_H - warp_info['out_h'] * scale) / 2
        cx = int(x * scale + x_off)
        cy = int(y * scale + y_off)
        cw = max(1, int(w * scale))
        ch = max(1, int(h * scale))
        return cx, cy, cw, ch
