"""
FRLG Shiny Starter — 3DS

Auto-generated by GamePRo Script Builder.
Adjust the timing constants at the top of the class to tune the script.
"""

import json
import os
import sys
import time

from scripts.base_script import BaseScript


class FrlgShinyStarter(BaseScript):
    NAME = 'FRLG Shiny Starter'
    DESCRIPTION = "Auto-generated script for 3DS."

    # ── Timing constants (seconds) ──────────────────────────────────────
    SOFT_RESET_1_DELAY = 1.63
    X_2_DELAY = 1.16
    A_3_DELAY = 1.84
    A_4_DELAY = 1.23
    A_5_DELAY = 6.71
    A_6_DELAY = 4.76
    A_7_DELAY = 3.35
    A_8_DELAY = 2.75
    B_9_DELAY = 3.49
    A_10_DELAY = 1.88
    A_11_DELAY = 1.92
    A_12_DELAY = 2.79
    A_13_DELAY = 5.76
    B_14_DELAY = 3.69
    A_15_DELAY = 4.56
    X_16_DELAY = 1.15
    A_17_DELAY = 1.75
    A_18_DELAY = 1.30
    A_19_DELAY = 0.00
    DETECT_1_WINDOW    = 5.0
    DETECT_1_INTERVAL  = 0.08
    DETECT_1_TOLERANCE = 30
    DETECT_1_TARGET   = [255.0, 216.0, 95.0]  # R, G, B target colour (right-click reference image)
    DETECT_1_PX_THRESHOLD = 10   # min matching pixels to trigger

    def __init__(self):
        super().__init__()
        self._cal = None

    def run(self, controller, frame_grabber, stop_event, log, request_calibration):
        log('Script started.')
        self._load_cal()

        # ── Screen crop (ask once; saved to cal file for subsequent runs) ──────
        if not self._cal or 'crop' not in self._cal:
            crop = request_calibration('Draw a rectangle around the game screen to crop the view.')
            if stop_event.is_set():
                return
            if self._cal is None:
                self._cal = {}
            self._cal['crop'] = list(crop)
            self._save_cal()
        frame_grabber.set_crop(*self._cal['crop'])
        log('Screen crop applied.')
        count = 0

        while not stop_event.is_set():
            # Step 1: [Home]
            controller.soft_reset()
            if not self.wait(self.SOFT_RESET_1_DELAY, stop_event): break

            # Step 2: [X]
            controller.press_x()
            if not self.wait(self.X_2_DELAY, stop_event): break

            # Step 3: [A]
            controller.press_a()
            if not self.wait(self.A_3_DELAY, stop_event): break

            # Step 4: [A]
            controller.press_a()
            if not self.wait(self.A_4_DELAY, stop_event): break

            # Step 5: [A]
            controller.press_a()
            if not self.wait(self.A_5_DELAY, stop_event): break

            # Step 6: [A]
            controller.press_a()
            if not self.wait(self.A_6_DELAY, stop_event): break

            # Step 7: [A]
            controller.press_a()
            if not self.wait(self.A_7_DELAY, stop_event): break

            # Step 8: [A]
            controller.press_a()
            if not self.wait(self.A_8_DELAY, stop_event): break

            # Step 9: [B]
            controller.press_b()
            if not self.wait(self.B_9_DELAY, stop_event): break

            # Step 10: [A]
            controller.press_a()
            if not self.wait(self.A_10_DELAY, stop_event): break

            # Step 11: [A]
            controller.press_a()
            if not self.wait(self.A_11_DELAY, stop_event): break

            # Step 12: [A]
            controller.press_a()
            if not self.wait(self.A_12_DELAY, stop_event): break

            # Step 13: [A]
            controller.press_a()
            if not self.wait(self.A_13_DELAY, stop_event): break

            # Step 14: [B]
            controller.press_b()
            if not self.wait(self.B_14_DELAY, stop_event): break

            # Step 15: [A]
            controller.press_a()
            if not self.wait(self.A_15_DELAY, stop_event): break

            # Step 16: [X]
            controller.press_x()
            if not self.wait(self.X_16_DELAY, stop_event): break

            # Step 17: [A]
            controller.press_a()
            if not self.wait(self.A_17_DELAY, stop_event): break

            # Step 18: [A]
            controller.press_a()
            if not self.wait(self.A_18_DELAY, stop_event): break

            # Step 19: [A]
            controller.press_a()

            # Step 20: Detect
            if not self._cal or "region" not in self._cal:
                self._do_calibrate(request_calibration, frame_grabber, stop_event)
                if stop_event.is_set(): break
            x, y, w, h = self._cal['region']
            tr, tg, tb = self.DETECT_1_TARGET
            tol = self.DETECT_1_TOLERANCE
            frame_grabber.set_detect_overlay(x, y, w, h)
            result = self._poll_target_color(
                frame_grabber, stop_event,
                x, y, w, h, tr, tg, tb, tol,
                self.DETECT_1_PX_THRESHOLD,
                self.DETECT_1_WINDOW, self.DETECT_1_INTERVAL, log)
            frame_grabber.clear_detect_overlay()
            if stop_event.is_set(): break
            if result is not None:
                log(f'DETECTED! {result} px match target colour (threshold: {self.DETECT_1_PX_THRESHOLD}).')
                stop_event.wait()
                break

            count += 1
            log(f'Attempt {count} complete.')

        frame_grabber.clear_crop()

        log('Script stopped.')

    # ── Calibration ──────────────────────────────────────────────────────

    def _cal_path(self):
        base = (os.path.dirname(sys.executable) if getattr(sys, 'frozen', False)
                else os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        cal_dir = os.path.join(base, 'calibration')
        os.makedirs(cal_dir, exist_ok=True)
        return os.path.join(cal_dir, 'frlg_shiny_starter.json')

    def _load_cal(self):
        try:
            with open(self._cal_path(), 'r') as f:
                self._cal = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            self._cal = None

    def _save_cal(self):
        with open(self._cal_path(), 'w') as f:
            json.dump(self._cal, f)

    def _do_calibrate(self, request_calibration, frame_grabber, stop_event):
        """Called the first time the detect step is reached."""
        region = request_calibration(
            "Draw a box around the area to watch for changes.")
        if stop_event.is_set():
            return
        x, y, w, h = region
        frame = frame_grabber.get_latest_frame()
        if frame is None:
            return
        r, g, b = self.avg_rgb(frame, x, y, w, h)
        if self._cal is None:
            self._cal = {}
        self._cal.update({'region': [x, y, w, h], 'baseline': [r, g, b], 'tolerance': 25})
        self._save_cal()

    def _poll_target_color(self, frame_grabber, stop_event,
                          x, y, w, h, tr, tg, tb, tolerance,
                          px_threshold, window, interval, log=None):
        """Target colour detection — fires when >= px_threshold pixels
        match the target colour (tr, tg, tb) within tolerance.
        Use for detecting a specific sparkle/highlight colour.
        """
        deadline = time.time() + window
        next_log = time.time() + 2.0
        while time.time() < deadline:
            if stop_event.is_set():
                return None
            frame = frame_grabber.get_latest_frame()
            if frame is not None:
                n = self.count_target_pixels(
                    frame, x, y, w, h, tr, tg, tb, tolerance)
                if log and time.time() >= next_log:
                    log(f'Watching... {n} px match target  (threshold: {px_threshold}  tolerance: {tolerance})')
                    next_log = time.time() + 2.0
                if n >= px_threshold:
                    time.sleep(interval * 2)
                    frame2 = frame_grabber.get_latest_frame()
                    if frame2 is not None:
                        n2 = self.count_target_pixels(
                            frame2, x, y, w, h, tr, tg, tb, tolerance)
                        if n2 >= px_threshold:
                            return n2
            time.sleep(interval)
        return None
